// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwnYMBHI2uoItIUwy5arcay1D6n0LaOg',
    appId: '1:994520086138:web:c39f0dc9f628d22776adc3',
    messagingSenderId: '994520086138',
    projectId: 'my-iiit-44555',
    authDomain: 'my-iiit-44555.firebaseapp.com',
    storageBucket: 'my-iiit-44555.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa1MDejdqLRbGJuQGJ8nkCmkcGgr7kskY',
    appId: '1:994520086138:android:2c3111de23ee8f2576adc3',
    messagingSenderId: '994520086138',
    projectId: 'my-iiit-44555',
    storageBucket: 'my-iiit-44555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl0BqN1NuRcwTl2wqcV5qN9tqw9NPpqJE',
    appId: '1:994520086138:ios:d7d027535ff9fc6c76adc3',
    messagingSenderId: '994520086138',
    projectId: 'my-iiit-44555',
    storageBucket: 'my-iiit-44555.appspot.com',
    iosClientId: '994520086138-6op3o1qk8ioh0mcm16jj0ah2a3j0uhmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myIiit',
  );
}
